// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL4cDt3SzorLyuzevscCRiwhrKXXuh6qQ',
    appId: '1:510491987865:web:c5ace388bc83d89e864d08',
    messagingSenderId: '510491987865',
    projectId: 'geonotes-8424e',
    authDomain: 'geonotes-8424e.firebaseapp.com',
    storageBucket: 'geonotes-8424e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-NftPK9CGrsnLeAYF64uZfTRa01nK7og',
    appId: '1:510491987865:android:610218b9587fd407864d08',
    messagingSenderId: '510491987865',
    projectId: 'geonotes-8424e',
    storageBucket: 'geonotes-8424e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQoc-yajWwI9ZwTvFtfALhUTQcHAmKBpI',
    appId: '1:510491987865:ios:6ed487acf0caa646864d08',
    messagingSenderId: '510491987865',
    projectId: 'geonotes-8424e',
    storageBucket: 'geonotes-8424e.appspot.com',
    iosBundleId: 'com.example.geonotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQoc-yajWwI9ZwTvFtfALhUTQcHAmKBpI',
    appId: '1:510491987865:ios:6ed487acf0caa646864d08',
    messagingSenderId: '510491987865',
    projectId: 'geonotes-8424e',
    storageBucket: 'geonotes-8424e.appspot.com',
    iosBundleId: 'com.example.geonotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBL4cDt3SzorLyuzevscCRiwhrKXXuh6qQ',
    appId: '1:510491987865:web:18efe433b03456d9864d08',
    messagingSenderId: '510491987865',
    projectId: 'geonotes-8424e',
    authDomain: 'geonotes-8424e.firebaseapp.com',
    storageBucket: 'geonotes-8424e.appspot.com',
  );
}
